<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="9.0.20" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Portal.Api\Portal.Api.csproj" />
    <ProjectReference Include="..\..\src\Portal.Core\Portal.Core.csproj" />
    <ProjectReference Include="..\..\src\Modules\Portal.Modules.Perfil\Portal.Modules.Perfil.csproj" />
    <ProjectReference Include="..\..\src\Modules\Portal.Modules.Apoios\Portal.Modules.Apoios.csproj" />
    <ProjectReference Include="..\..\src\Modules\Portal.Modules.Anuncios\Portal.Modules.Anuncios.csproj" />
    <ProjectReference Include="..\..\src\Modules\Portal.Modules.Carro\Portal.Modules.Carro.csproj" />
    <ProjectReference Include="..\..\src\Modules\Portal.Modules.Investimentos\Portal.Modules.Investimentos.csproj" />
    <ProjectReference Include="..\..\src\Modules\Portal.Modules.Assistente\Portal.Modules.Assistente.csproj" />
  </ItemGroup>

</Project>
